# https://golangci-lint.run/usage/linters/
linters:
  enable-all: true
  disable:
    - depguard
    - nlreturn
    - exportloopref
    - wsl # only one cuddle assignment allowed before range statement
