version: "2"
linters:
    default: all
    disable:
        - depguard
        - exhaustruct
        - godot
        - godox
        - intrange
        - lll
        - mnd
        - nlreturn
        - varnamelen
        - wsl
    exclusions:
        generated: lax
        presets:
            - comments
            - common-false-positives
            - legacy
            - std-error-handling
        rules:
            - linters:
                  - cyclop
                  - forbidigo
                  - funlen
                  - govet
                  - varnamelen
              path: _test\.go$
        paths:
            - third_party$
            - builtin$
            - examples$
formatters:
    enable:
        - gci
        - gofmt
        - gofumpt
        - goimports
    exclusions:
        generated: lax
        paths:
            - third_party$
            - builtin$
            - examples$
