# https://golangci-lint.run/usage/linters/
linters:
  enable-all: true
  disable:
    - intrange
    - depguard
    - nlreturn
    - exportloopref
    - wsl # only one cuddle assignment allowed before range statement
    - lll # line length limit
    - godox
    - godot
    - mnd
    - exhaustruct

issues:
  exclude-rules:
    - linters:
        - funlen
        - cyclop
        - varnamelen
      path: _test\.go$
